// Code generated by ogen, DO NOT EDIT.

package adminapi

// OperationName is the ogen operation name
type OperationName = string

const (
	ApproveHostOperation OperationName = "ApproveHost"
	ListHostsOperation   OperationName = "ListHosts"
	RevokeHostOperation  OperationName = "RevokeHost"
)
