// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { ApproveHostData, ApproveHostErrors, ApproveHostResponses, ListHostsData, ListHostsErrors, ListHostsResponses, RevokeHostData, RevokeHostErrors, RevokeHostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List hosts
 *
 * Every enrolled host, with what it reported about itself.
 */
export const listHosts = <ThrowOnError extends boolean = false>(options?: Options<ListHostsData, ThrowOnError>): RequestResult<ListHostsResponses, ListHostsErrors, ThrowOnError> => (options?.client ?? client).get<ListHostsResponses, ListHostsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/hosts',
    ...options
});

/**
 * Approve a pending host
 *
 * The code is what the worker printed when it enrolled. A worker started with the operator's join token skips this and is approved on hello. 409 when the host is not pending; 400 when the code does not match.
 */
export const approveHost = <ThrowOnError extends boolean = false>(options: Options<ApproveHostData, ThrowOnError>): RequestResult<ApproveHostResponses, ApproveHostErrors, ThrowOnError> => (options.client ?? client).post<ApproveHostResponses, ApproveHostErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/hosts/{id}/approve',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Revoke a host
 *
 * The host is rejected on its next hello, and on the socket it is holding now. The row stays — a revoked host is remembered, not removed.
 */
export const revokeHost = <ThrowOnError extends boolean = false>(options: Options<RevokeHostData, ThrowOnError>): RequestResult<RevokeHostResponses, RevokeHostErrors, ThrowOnError> => (options.client ?? client).post<RevokeHostResponses, RevokeHostErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/hosts/{id}/revoke',
    ...options
});
