// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type ApproveBody = {
    /**
     * What the worker printed when it enrolled.
     */
    code: string;
};

export type HostView = {
    id: string;
    name: string;
    status: 'pending' | 'approved' | 'revoked';
    /**
     * What the worker printed. Present only while the host is pending.
     */
    approve_code?: string;
    /**
     * Tunnel connected right now.
     */
    online: boolean;
    /**
     * Present only while the host is online.
     */
    capacity?: Capacity;
    /**
     * What this host reported in its last hello.
     */
    tags: Array<string>;
    last_seen_at: number | null;
    created_at: number;
};

export type Capacity = {
    running: number;
    max: number;
};

export type ErrorModel = {
    /**
     * The first problem, in prose.
     */
    error: string;
    /**
     * Every failing field, for validation errors.
     */
    issues?: Array<Issue>;
};

export type Issue = {
    /**
     * The field a caller has to fix, as they sent it.
     */
    path?: string;
    message: string;
};

export type HostId = string;

export type ListHostsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/hosts';
};

export type ListHostsErrors = {
    /**
     * Every failure. `error` is the first problem in prose; `issues` names each failing field when the request did not validate.
     */
    default: ErrorModel;
};

export type ListHostsError = ListHostsErrors[keyof ListHostsErrors];

export type ListHostsResponses = {
    /**
     * Every enrolled host, oldest first.
     */
    200: Array<HostView>;
};

export type ListHostsResponse = ListHostsResponses[keyof ListHostsResponses];

export type ApproveHostData = {
    body: ApproveBody;
    path: {
        id: string;
    };
    query?: never;
    url: '/hosts/{id}/approve';
};

export type ApproveHostErrors = {
    /**
     * Every failure. `error` is the first problem in prose; `issues` names each failing field when the request did not validate.
     */
    default: ErrorModel;
};

export type ApproveHostError = ApproveHostErrors[keyof ApproveHostErrors];

export type ApproveHostResponses = {
    /**
     * Approved. The socket it is holding is promoted, so the worker does not have to reconnect to find out.
     */
    204: void;
};

export type ApproveHostResponse = ApproveHostResponses[keyof ApproveHostResponses];

export type RevokeHostData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/hosts/{id}/revoke';
};

export type RevokeHostErrors = {
    /**
     * Every failure. `error` is the first problem in prose; `issues` names each failing field when the request did not validate.
     */
    default: ErrorModel;
};

export type RevokeHostError = RevokeHostErrors[keyof RevokeHostErrors];

export type RevokeHostResponses = {
    /**
     * Revoked.
     */
    204: void;
};

export type RevokeHostResponse = RevokeHostResponses[keyof RevokeHostResponses];
