// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"fmt"

	"github.com/go-faster/errors"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// AttachTerminalSwitchingProtocols is response for AttachTerminal operation.
type AttachTerminalSwitchingProtocols struct{}

type Bearer struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *Bearer) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *Bearer) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *Bearer) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *Bearer) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/CreateSandbox
type CreateSandbox struct {
	Image string `json:"image"`
	// Exec'd in the PTY. Omit for the image's own default entry.
	Cmd []string `json:"cmd"`
	// Ended after this long without PTY traffic in either direction. Default 1800.
	IdleTimeoutS OptInt `json:"idle_timeout_s"`
	// Persisted, and visible in the API.
	Env OptCreateSandboxEnv `json:"env"`
	// Forwarded to the worker and never persisted or shown. The only place a secret travels; no row ever
	// holds one.
	SecretEnv OptCreateSandboxSecretEnv `json:"secret_env"`
	// Host tags this sandbox requires. Only hosts carrying all of them are candidates. TERM and
	// SANDBOXD_SESSION_ID are reserved env names and are refused in either map.
	Tags []string `json:"tags"`
}

// GetImage returns the value of Image.
func (s *CreateSandbox) GetImage() string {
	return s.Image
}

// GetCmd returns the value of Cmd.
func (s *CreateSandbox) GetCmd() []string {
	return s.Cmd
}

// GetIdleTimeoutS returns the value of IdleTimeoutS.
func (s *CreateSandbox) GetIdleTimeoutS() OptInt {
	return s.IdleTimeoutS
}

// GetEnv returns the value of Env.
func (s *CreateSandbox) GetEnv() OptCreateSandboxEnv {
	return s.Env
}

// GetSecretEnv returns the value of SecretEnv.
func (s *CreateSandbox) GetSecretEnv() OptCreateSandboxSecretEnv {
	return s.SecretEnv
}

// GetTags returns the value of Tags.
func (s *CreateSandbox) GetTags() []string {
	return s.Tags
}

// SetImage sets the value of Image.
func (s *CreateSandbox) SetImage(val string) {
	s.Image = val
}

// SetCmd sets the value of Cmd.
func (s *CreateSandbox) SetCmd(val []string) {
	s.Cmd = val
}

// SetIdleTimeoutS sets the value of IdleTimeoutS.
func (s *CreateSandbox) SetIdleTimeoutS(val OptInt) {
	s.IdleTimeoutS = val
}

// SetEnv sets the value of Env.
func (s *CreateSandbox) SetEnv(val OptCreateSandboxEnv) {
	s.Env = val
}

// SetSecretEnv sets the value of SecretEnv.
func (s *CreateSandbox) SetSecretEnv(val OptCreateSandboxSecretEnv) {
	s.SecretEnv = val
}

// SetTags sets the value of Tags.
func (s *CreateSandbox) SetTags(val []string) {
	s.Tags = val
}

// Persisted, and visible in the API.
type CreateSandboxEnv map[string]string

func (s *CreateSandboxEnv) init() CreateSandboxEnv {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// Forwarded to the worker and never persisted or shown. The only place a secret travels; no row ever
// holds one.
type CreateSandboxSecretEnv map[string]string

func (s *CreateSandboxSecretEnv) init() CreateSandboxSecretEnv {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/ErrorModel
type ErrorModel struct {
	// The first problem, in prose.
	Error string `json:"error"`
	// Every failing field, for validation errors.
	Issues []Issue `json:"issues"`
}

// GetError returns the value of Error.
func (s *ErrorModel) GetError() string {
	return s.Error
}

// GetIssues returns the value of Issues.
func (s *ErrorModel) GetIssues() []Issue {
	return s.Issues
}

// SetError sets the value of Error.
func (s *ErrorModel) SetError(val string) {
	s.Error = val
}

// SetIssues sets the value of Issues.
func (s *ErrorModel) SetIssues(val []Issue) {
	s.Issues = val
}

// ErrorStatusCode wraps ErrorModel with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   ErrorModel
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() ErrorModel {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val ErrorModel) {
	s.Response = val
}

// Ref: #/components/schemas/Health
type Health struct {
	Ok bool `json:"ok"`
}

// GetOk returns the value of Ok.
func (s *Health) GetOk() bool {
	return s.Ok
}

// SetOk sets the value of Ok.
func (s *Health) SetOk(val bool) {
	s.Ok = val
}

// Ref: #/components/schemas/Issue
type Issue struct {
	// The field a caller has to fix, as they sent it.
	Path    OptString `json:"path"`
	Message string    `json:"message"`
}

// GetPath returns the value of Path.
func (s *Issue) GetPath() OptString {
	return s.Path
}

// GetMessage returns the value of Message.
func (s *Issue) GetMessage() string {
	return s.Message
}

// SetPath sets the value of Path.
func (s *Issue) SetPath(val OptString) {
	s.Path = val
}

// SetMessage sets the value of Message.
func (s *Issue) SetMessage(val string) {
	s.Message = val
}

// Ref: #/components/schemas/Link
type Link struct {
	// Open this from the browser. It carries its own credential.
	URL string `json:"url"`
	// How long the URL stays good. Mint another when it lapses.
	ExpiresInS int `json:"expires_in_s"`
}

// GetURL returns the value of URL.
func (s *Link) GetURL() string {
	return s.URL
}

// GetExpiresInS returns the value of ExpiresInS.
func (s *Link) GetExpiresInS() int {
	return s.ExpiresInS
}

// SetURL sets the value of URL.
func (s *Link) SetURL(val string) {
	s.URL = val
}

// SetExpiresInS sets the value of ExpiresInS.
func (s *Link) SetExpiresInS(val int) {
	s.ExpiresInS = val
}

// NewNilBool returns new NilBool with value set to v.
func NewNilBool(v bool) NilBool {
	return NilBool{
		Value: v,
	}
}

// NilBool is nullable bool.
type NilBool struct {
	Value bool
	Null  bool
}

// SetTo sets value to v.
func (o *NilBool) SetTo(v bool) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilBool) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilBool) SetToNull() {
	o.Null = true
	var v bool
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilBool) Get() (v bool, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewNilInt returns new NilInt with value set to v.
func NewNilInt(v int) NilInt {
	return NilInt{
		Value: v,
	}
}

// NilInt is nullable int.
type NilInt struct {
	Value int
	Null  bool
}

// SetTo sets value to v.
func (o *NilInt) SetTo(v int) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilInt) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilInt) SetToNull() {
	o.Null = true
	var v int
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilInt) Get() (v int, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewNilInt64 returns new NilInt64 with value set to v.
func NewNilInt64(v int64) NilInt64 {
	return NilInt64{
		Value: v,
	}
}

// NilInt64 is nullable int64.
type NilInt64 struct {
	Value int64
	Null  bool
}

// SetTo sets value to v.
func (o *NilInt64) SetTo(v int64) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilInt64) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilInt64) SetToNull() {
	o.Null = true
	var v int64
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilInt64) Get() (v int64, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewNilSandboxViewEndedReason returns new NilSandboxViewEndedReason with value set to v.
func NewNilSandboxViewEndedReason(v SandboxViewEndedReason) NilSandboxViewEndedReason {
	return NilSandboxViewEndedReason{
		Value: v,
	}
}

// NilSandboxViewEndedReason is nullable SandboxViewEndedReason.
type NilSandboxViewEndedReason struct {
	Value SandboxViewEndedReason
	Null  bool
}

// SetTo sets value to v.
func (o *NilSandboxViewEndedReason) SetTo(v SandboxViewEndedReason) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilSandboxViewEndedReason) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilSandboxViewEndedReason) SetToNull() {
	o.Null = true
	var v SandboxViewEndedReason
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilSandboxViewEndedReason) Get() (v SandboxViewEndedReason, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilSandboxViewEndedReason) Or(d SandboxViewEndedReason) SandboxViewEndedReason {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewNilString returns new NilString with value set to v.
func NewNilString(v string) NilString {
	return NilString{
		Value: v,
	}
}

// NilString is nullable string.
type NilString struct {
	Value string
	Null  bool
}

// SetTo sets value to v.
func (o *NilString) SetTo(v string) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilString) SetToNull() {
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateSandboxEnv returns new OptCreateSandboxEnv with value set to v.
func NewOptCreateSandboxEnv(v CreateSandboxEnv) OptCreateSandboxEnv {
	return OptCreateSandboxEnv{
		Value: v,
		Set:   true,
	}
}

// OptCreateSandboxEnv is optional CreateSandboxEnv.
type OptCreateSandboxEnv struct {
	Value CreateSandboxEnv
	Set   bool
}

// IsSet returns true if OptCreateSandboxEnv was set.
func (o OptCreateSandboxEnv) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateSandboxEnv) Reset() {
	var v CreateSandboxEnv
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateSandboxEnv) SetTo(v CreateSandboxEnv) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateSandboxEnv) Get() (v CreateSandboxEnv, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateSandboxEnv) Or(d CreateSandboxEnv) CreateSandboxEnv {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateSandboxSecretEnv returns new OptCreateSandboxSecretEnv with value set to v.
func NewOptCreateSandboxSecretEnv(v CreateSandboxSecretEnv) OptCreateSandboxSecretEnv {
	return OptCreateSandboxSecretEnv{
		Value: v,
		Set:   true,
	}
}

// OptCreateSandboxSecretEnv is optional CreateSandboxSecretEnv.
type OptCreateSandboxSecretEnv struct {
	Value CreateSandboxSecretEnv
	Set   bool
}

// IsSet returns true if OptCreateSandboxSecretEnv was set.
func (o OptCreateSandboxSecretEnv) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateSandboxSecretEnv) Reset() {
	var v CreateSandboxSecretEnv
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateSandboxSecretEnv) SetTo(v CreateSandboxSecretEnv) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateSandboxSecretEnv) Get() (v CreateSandboxSecretEnv, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateSandboxSecretEnv) Or(d CreateSandboxSecretEnv) CreateSandboxSecretEnv {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PreviewBody
type PreviewBody struct {
	// The port inside the sandbox to expose.
	Port int `json:"port"`
}

// GetPort returns the value of Port.
func (s *PreviewBody) GetPort() int {
	return s.Port
}

// SetPort sets the value of Port.
func (s *PreviewBody) SetPort(val int) {
	s.Port = val
}

// Ref: #/components/schemas/SandboxView
type SandboxView struct {
	ID      string            `json:"id"`
	OwnerID string            `json:"owner_id"`
	Status  SandboxViewStatus `json:"status"`
	// Null until the sandbox is placed.
	HostID NilString `json:"host_id"`
	// Live, not stored. Null while the sandbox has no host.
	HostOnline NilBool `json:"host_online"`
	// 1-based, and only while queued.
	QueuePosition NilInt                    `json:"queue_position"`
	EndedReason   NilSandboxViewEndedReason `json:"ended_reason"`
	EndedDetail   NilString                 `json:"ended_detail"`
	Image         string                    `json:"image"`
	// Empty means the image's own default entry.
	Cmd []string       `json:"cmd"`
	Env SandboxViewEnv `json:"env"`
	// What this sandbox requires, not what its host carries.
	Tags         []string `json:"tags"`
	IdleTimeoutS int      `json:"idle_timeout_s"`
	// Unix milliseconds.
	CreatedAt int64    `json:"created_at"`
	StartedAt NilInt64 `json:"started_at"`
	EndedAt   NilInt64 `json:"ended_at"`
}

// GetID returns the value of ID.
func (s *SandboxView) GetID() string {
	return s.ID
}

// GetOwnerID returns the value of OwnerID.
func (s *SandboxView) GetOwnerID() string {
	return s.OwnerID
}

// GetStatus returns the value of Status.
func (s *SandboxView) GetStatus() SandboxViewStatus {
	return s.Status
}

// GetHostID returns the value of HostID.
func (s *SandboxView) GetHostID() NilString {
	return s.HostID
}

// GetHostOnline returns the value of HostOnline.
func (s *SandboxView) GetHostOnline() NilBool {
	return s.HostOnline
}

// GetQueuePosition returns the value of QueuePosition.
func (s *SandboxView) GetQueuePosition() NilInt {
	return s.QueuePosition
}

// GetEndedReason returns the value of EndedReason.
func (s *SandboxView) GetEndedReason() NilSandboxViewEndedReason {
	return s.EndedReason
}

// GetEndedDetail returns the value of EndedDetail.
func (s *SandboxView) GetEndedDetail() NilString {
	return s.EndedDetail
}

// GetImage returns the value of Image.
func (s *SandboxView) GetImage() string {
	return s.Image
}

// GetCmd returns the value of Cmd.
func (s *SandboxView) GetCmd() []string {
	return s.Cmd
}

// GetEnv returns the value of Env.
func (s *SandboxView) GetEnv() SandboxViewEnv {
	return s.Env
}

// GetTags returns the value of Tags.
func (s *SandboxView) GetTags() []string {
	return s.Tags
}

// GetIdleTimeoutS returns the value of IdleTimeoutS.
func (s *SandboxView) GetIdleTimeoutS() int {
	return s.IdleTimeoutS
}

// GetCreatedAt returns the value of CreatedAt.
func (s *SandboxView) GetCreatedAt() int64 {
	return s.CreatedAt
}

// GetStartedAt returns the value of StartedAt.
func (s *SandboxView) GetStartedAt() NilInt64 {
	return s.StartedAt
}

// GetEndedAt returns the value of EndedAt.
func (s *SandboxView) GetEndedAt() NilInt64 {
	return s.EndedAt
}

// SetID sets the value of ID.
func (s *SandboxView) SetID(val string) {
	s.ID = val
}

// SetOwnerID sets the value of OwnerID.
func (s *SandboxView) SetOwnerID(val string) {
	s.OwnerID = val
}

// SetStatus sets the value of Status.
func (s *SandboxView) SetStatus(val SandboxViewStatus) {
	s.Status = val
}

// SetHostID sets the value of HostID.
func (s *SandboxView) SetHostID(val NilString) {
	s.HostID = val
}

// SetHostOnline sets the value of HostOnline.
func (s *SandboxView) SetHostOnline(val NilBool) {
	s.HostOnline = val
}

// SetQueuePosition sets the value of QueuePosition.
func (s *SandboxView) SetQueuePosition(val NilInt) {
	s.QueuePosition = val
}

// SetEndedReason sets the value of EndedReason.
func (s *SandboxView) SetEndedReason(val NilSandboxViewEndedReason) {
	s.EndedReason = val
}

// SetEndedDetail sets the value of EndedDetail.
func (s *SandboxView) SetEndedDetail(val NilString) {
	s.EndedDetail = val
}

// SetImage sets the value of Image.
func (s *SandboxView) SetImage(val string) {
	s.Image = val
}

// SetCmd sets the value of Cmd.
func (s *SandboxView) SetCmd(val []string) {
	s.Cmd = val
}

// SetEnv sets the value of Env.
func (s *SandboxView) SetEnv(val SandboxViewEnv) {
	s.Env = val
}

// SetTags sets the value of Tags.
func (s *SandboxView) SetTags(val []string) {
	s.Tags = val
}

// SetIdleTimeoutS sets the value of IdleTimeoutS.
func (s *SandboxView) SetIdleTimeoutS(val int) {
	s.IdleTimeoutS = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *SandboxView) SetCreatedAt(val int64) {
	s.CreatedAt = val
}

// SetStartedAt sets the value of StartedAt.
func (s *SandboxView) SetStartedAt(val NilInt64) {
	s.StartedAt = val
}

// SetEndedAt sets the value of EndedAt.
func (s *SandboxView) SetEndedAt(val NilInt64) {
	s.EndedAt = val
}

type SandboxViewEndedReason string

const (
	SandboxViewEndedReasonClosed SandboxViewEndedReason = "closed"
	SandboxViewEndedReasonIdle   SandboxViewEndedReason = "idle"
	SandboxViewEndedReasonFailed SandboxViewEndedReason = "failed"
	SandboxViewEndedReasonLost   SandboxViewEndedReason = "lost"
	SandboxViewEndedReasonExited SandboxViewEndedReason = "exited"
)

// AllValues returns all SandboxViewEndedReason values.
func (SandboxViewEndedReason) AllValues() []SandboxViewEndedReason {
	return []SandboxViewEndedReason{
		SandboxViewEndedReasonClosed,
		SandboxViewEndedReasonIdle,
		SandboxViewEndedReasonFailed,
		SandboxViewEndedReasonLost,
		SandboxViewEndedReasonExited,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SandboxViewEndedReason) MarshalText() ([]byte, error) {
	switch s {
	case SandboxViewEndedReasonClosed:
		return []byte(s), nil
	case SandboxViewEndedReasonIdle:
		return []byte(s), nil
	case SandboxViewEndedReasonFailed:
		return []byte(s), nil
	case SandboxViewEndedReasonLost:
		return []byte(s), nil
	case SandboxViewEndedReasonExited:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SandboxViewEndedReason) UnmarshalText(data []byte) error {
	switch SandboxViewEndedReason(data) {
	case SandboxViewEndedReasonClosed:
		*s = SandboxViewEndedReasonClosed
		return nil
	case SandboxViewEndedReasonIdle:
		*s = SandboxViewEndedReasonIdle
		return nil
	case SandboxViewEndedReasonFailed:
		*s = SandboxViewEndedReasonFailed
		return nil
	case SandboxViewEndedReasonLost:
		*s = SandboxViewEndedReasonLost
		return nil
	case SandboxViewEndedReasonExited:
		*s = SandboxViewEndedReasonExited
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type SandboxViewEnv map[string]string

func (s *SandboxViewEnv) init() SandboxViewEnv {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

type SandboxViewStatus string

const (
	SandboxViewStatusQueued   SandboxViewStatus = "queued"
	SandboxViewStatusCreating SandboxViewStatus = "creating"
	SandboxViewStatusRunning  SandboxViewStatus = "running"
	SandboxViewStatusEnded    SandboxViewStatus = "ended"
)

// AllValues returns all SandboxViewStatus values.
func (SandboxViewStatus) AllValues() []SandboxViewStatus {
	return []SandboxViewStatus{
		SandboxViewStatusQueued,
		SandboxViewStatusCreating,
		SandboxViewStatusRunning,
		SandboxViewStatusEnded,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SandboxViewStatus) MarshalText() ([]byte, error) {
	switch s {
	case SandboxViewStatusQueued:
		return []byte(s), nil
	case SandboxViewStatusCreating:
		return []byte(s), nil
	case SandboxViewStatusRunning:
		return []byte(s), nil
	case SandboxViewStatusEnded:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SandboxViewStatus) UnmarshalText(data []byte) error {
	switch SandboxViewStatus(data) {
	case SandboxViewStatusQueued:
		*s = SandboxViewStatusQueued
		return nil
	case SandboxViewStatusCreating:
		*s = SandboxViewStatusCreating
		return nil
	case SandboxViewStatusRunning:
		*s = SandboxViewStatusRunning
		return nil
	case SandboxViewStatusEnded:
		*s = SandboxViewStatusEnded
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
