// Code generated by ogen, DO NOT EDIT.

package openapi

// OperationName is the ogen operation name
type OperationName = string

const (
	AttachTerminalOperation OperationName = "AttachTerminal"
	CreateSandboxOperation  OperationName = "CreateSandbox"
	EndSandboxOperation     OperationName = "EndSandbox"
	GetSandboxOperation     OperationName = "GetSandbox"
	HealthzOperation        OperationName = "Healthz"
	ListSandboxesOperation  OperationName = "ListSandboxes"
	OpenPreviewOperation    OperationName = "OpenPreview"
	OpenTerminalOperation   OperationName = "OpenTerminal"
)
